workspace = { members = [
    "ch01",
    "ch02",
    "ch03",
    "ch04",
    "ch05",
    "ch06",
    "ch07",
<<<<<<< HEAD
=======
    "ch08",
    "ch09",
    "ch10",
    "ch11",
    "ch12",
>>>>>>> 498f4aa1388d1f9bf5c2ae758c1043ea1f9f67bf
] }
